sonar.projectKey=auth-oficinapro
sonar.organization=oficinapro

# Paths
sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,**/mocks/**,**/*.pb.go,**/bootstrap,**/bin/**,**/scripts/**,**/*.yml,**/*.yaml,**/*.md

# Tests
sonar.tests=.
sonar.test.inclusions=**/*_test.go

# Coverage
sonar.go.coverage.reportPaths=coverage.out

# Encoding
sonar.sourceEncoding=UTF-8

# Quality Gate
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300

# Language
sonar.language=go

# Links
sonar.links.homepage=https://github.com/oficinapro/auth-oficinapro
sonar.links.ci=https://github.com/oficinapro/auth-oficinapro/actions
sonar.links.scm=https://github.com/oficinapro/auth-oficinapro
sonar.links.issue=https://github.com/oficinapro/auth-oficinapro/issues

