apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oficinapro

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml

commonLabels:
  app.kubernetes.io/name: order-service
  app.kubernetes.io/part-of: oficinapro
  app.kubernetes.io/managed-by: kubectl

images:
- name: order-service
  newName: 123456789.dkr.ecr.us-east-1.amazonaws.com/order-service
  newTag: v1.0.0

